[package]
name = "lumalla_screencast"
version = "0.1.0"
edition = "2024"
description = "PipeWire screencast stream helper for Lumalla"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lumalla/lumalla"
include = ["src/**/*", "LICENSE-*"]

[dependencies]
anyhow = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
once_cell = "1"
pipewire = { version = "0.9", features = ["v0_3_65"] }
