[package]
name = "lumalla_wayland_protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
calloop = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
lumalla_wayland_protocol_macros = { path = "../lumalla_wayland_protocol_macros" }
